# the training minibatch size
BATCH_SIZE = 8
# the number of history frames to give as input to the network
HIST_LEN = 4
# the number of frames generated by the network
OUT_LEN = 2

PADDING_G = 'SAME'
LRATE_G = 0.0004

PADDING_D = 'SAME'